name: Android Super Partition Repack (Final, Reliable Method)

on:
  workflow_dispatch:
    inputs:
      stock_firmware_url:
        description: 'URL to the stock firmware (Direct HTTP, MEGA.nz, etc.). Find the real link manually.'
        required: true
        type: string
      custom_system_url:
        description: 'Custom ROM download URL (.img, .img.xz, .img.gz, .zip supported)'
        required: true
        type: string
      empty_product:
        description: 'Use empty product.img (-e flag)'
        required: false
        type: boolean
        default: false
      empty_system_ext:
        description: 'Use empty system_ext.img (-x flag)'
        required: false
        type: boolean
        default: false
      silent_mode:
        description: 'Silent mode (-s flag)'
        required: false
        type: boolean
        default: true
      writable:
        description: 'Make partitions writable (-w flag)'
        required: false
        type: boolean
        default: false
      purge_all:
        description: 'Purge repacksuper directory (-p flag)'
        required: false
        type: boolean
        default: false

jobs:
  repack-super:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        echo "==> Installing required OS packages..."
        sudo apt-get update
        sudo apt-get install -y \
          android-sdk-libsparse-utils \
          tar \
          xz-utils \
          liblz4-tool \
          unzip \
          gzip \
          file \
          wget \
          curl \
          megatools # For MEGA.nz support
        echo "✓ Dependencies installed."

    - name: Verify repacksuper.sh exists
      run: |
        if [ ! -f "./repacksuper.sh" ]; then echo "✗ Error: repacksuper.sh not found" && exit 1; fi
        chmod +x ./repacksuper.sh

    - name: Create working directory
      run: mkdir -p work

    - name: Download and Extract Stock Firmware
      run: |
        cd work
        FIRMWARE_URL="${{ github.event.inputs.stock_firmware_url }}"
        
        # Check if the URL is a MEGA.nz link and use the correct tool
        if [[ $FIRMWARE_URL == *"mega.nz"* ]]; then
          echo "==> MEGA.nz link detected. Downloading with megatools..."
          megadl "$FIRMWARE_URL"
        else
          echo "==> Direct HTTP link detected. Downloading with wget..."
          # Use --content-disposition to handle generic server links that don't have a filename in the URL
          wget --content-disposition "$FIRMWARE_URL"
        fi
        
        # Verify that a file was downloaded, regardless of the method
        if ! ls *.zip 1> /dev/null 2>&1; then
          echo "✗ CRITICAL ERROR: Failed to download stock firmware, or the downloaded file was not a .zip archive."
          exit 1
        fi
        
        FIRMWARE_ZIP=$(ls *.zip | head -n 1)
        echo "✓ Stock firmware downloaded successfully: $FIRMWARE_ZIP"
        
        echo "==> Unzipping firmware package..."
        unzip -o "$FIRMWARE_ZIP"
        
        AP_FILE=$(find . -name "AP_*.tar.md5" | head -n 1)
        if [ -z "$AP_FILE" ]; then echo "✗ Error: AP file not found in the unzipped firmware." && ls -lR && exit 1; fi
        echo "✓ Found AP file: $AP_FILE"
        
        echo "==> Extracting and preparing super.img..."
        tar -xvf "$AP_FILE" super.img.sparse.lz4
        if [ ! -f "super.img.sparse.lz4" ]; then echo "✗ Error: Could not extract super.img.sparse.lz4 from the AP file." && exit 1; fi
        
        lz4 -d super.img.sparse.lz4 stock_super_sparse.img
        simg2img stock_super_sparse.img stock_super.img
        
        if [ ! -f "stock_super.img" ]; then echo "✗ Error: Failed to create raw stock_super.img." && exit 1; fi
        echo "✓ stock_super.img prepared successfully!"

    - name: Download and Prepare Custom system.img
      run: |
        cd work
        echo "==> Downloading custom ROM package..."
        wget -O custom_rom_package "${{ github.event.inputs.custom_system_url }}"
        if [ ! -s "custom_rom_package" ]; then echo "✗ Error: Failed to download custom ROM." && exit 1; fi
        
        FILE_TYPE=$(file -b custom_rom_package)
        echo "File type detected: $FILE_TYPE"
        case "$FILE_TYPE" in
          *"XZ compressed data"*)      mv custom_rom_package custom_system.img.xz && unxz custom_system.img.xz ;;
          *"gzip compressed data"*)    mv custom_rom_package custom_system.img.gz && gunzip custom_system.img.gz ;;
          *"Zip archive data"*)
            unzip -o custom_rom_package
            SYSTEM_IMG_FILE=$(find . -maxdepth 1 -name "system.img" -o -name "system.raw.img" | head -n 1)
            if [ -z "$SYSTEM_IMG_FILE" ]; then echo "✗ Error: system.img not found in ZIP." && ls -lR && exit 1; fi
            mv "$SYSTEM_IMG_FILE" custom_system.img ;;
          *"Android sparse image"*)    mv custom_rom_package c_sparse.img && simg2img c_sparse.img custom_system.img ;;
          *"ext4 filesystem data"*)    mv custom_rom_package custom_system.img ;;
          *)                            echo "✗ Error: Unsupported file type: $FILE_TYPE" && exit 1 ;;
        esac
        if [ ! -f "custom_system.img" ]; then echo "✗ Error: custom_system.img not created." && exit 1; fi
        echo "✓ Custom system.img prepared successfully!"

    - name: Prepare repacksuper.sh flags
      id: prepare_flags
      run: |
        FLAGS=""
        if [ "${{ github.event.inputs.empty_product }}" == "true" ]; then FLAGS="$FLAGS -e"; fi
        if [ "${{ github.event.inputs.empty_system_ext }}" == "true" ]; then FLAGS="$FLAGS -x"; fi
        if [ "${{ github.event.inputs.silent_mode }}" == "true" ]; then FLAGS="$FLAGS -s"; fi
        if [ "${{ github.event.inputs.writable }}" == "true" ]; then FLAGS="$FLAGS -w"; fi
        if [ "${{ github.event.inputs.purge_all }}" == "true" ]; then FLAGS="$FLAGS -p"; fi
        echo "flags=$FLAGS" >> $GITHUB_OUTPUT

    - name: Run repacksuper.sh
      run: |
        cd work
        echo "==> Running repacksuper.sh with flags: ${{ steps.prepare_flags.outputs.flags }}"
        ../repacksuper.sh ${{ steps.prepare_flags.outputs.flags }} -r "$(pwd)" stock_super.img custom_system.img repacked_super.img

    - name: Verify output and Create Tarball
      run: |
        cd work
        if [ ! -f "repacked_super.img" ]; then echo "✗ Error: repacked_super.img not found." && ls -la && exit 1; fi
        echo "✓ Repacked super.img created successfully."
        echo "==> Creating tar archive for Odin..."
        tar -cvf repacked_super.tar repacked_super.img
        echo "✓ Tar archive created."

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: repacked-super-img
        path: |
          work/repacked_super.img
          work/repacked_super.tar
        retention-days: 7

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failure-logs
        path: work/
        retention-days: 1

    - name: Display Completion Message
      run: |
        echo "======================================================="
        echo "  Android Super Partition Repack Complete"
        echo "======================================================="
        echo "✓ Stock firmware downloaded from your URL and processed"
        echo "✓ Custom ROM integrated"
        echo "✓ New super.img created and packaged"
        echo ""
        echo "Download the 'repacked-super-img' artifact below."
        echo "======================================================="
